### ISSUE TITLE
I have 4 million document in which I need to search for 90k words . In multiple thread performance of library do not increase.

### ISSUE THREAD

**Issue by avinashk12** [JanFan/py-aho-corasick#3]
I have 4 million document in which I need to search for 90k words . 
In multiple thread performance of library do not increase. 
lets say for one document it is taking 10 second and then for 6 document it is taking 1 min.  
But my assumption is that if i use 6 thread all 6 document should be processed in 10-12 sec.    
let me know if i want to process documents in parallel is this library suitable for my use case?

**Comment by Guangyi-Z** [comment]
Hi, @avinashk12 
If your program does not make use of multiple cores, it won't be faster. Given only one core, most of the running time has already been due to CPU time.
Besides, Python is notorious for its global interpreter lock, or GIL, which means usage of multiple cores is possible only by creating multiple processes, leading to multiple copies of your 4M docs that are too demanding for an average computer.
Lastly, it would be good if you can show your code.

**Comment by avinashk12** [comment]
Hi @JanFan  i have modified code and moved to spark (hadoop) for parallel processing . it worked. 
thanks for this library .
